openapi: "3.0.0"
info:
  title: History Service
  version: 0.0.1
servers:
- url: https://thing-history.apps.foresight.aareon.com/api/
  description: Foresight Thing Registry 
paths:
  /property/{thingId}/{propertyName}:
    get:
      description: Returns time series data for a thing property
      parameters:
      - name: thingId
        in: path
        description: ID of the thing
        required: true
        schema:
          type: string
      - name: propertyName
        in: path
        description: Name of the property
        required: true
        schema:
          type: string
      - name: start
        in: Query
        schema: 
          type: string
          format: date-time
      - name: stop
        in: Query
        schema: 
          type: string
          format: date-time
      responses:
        '200':
          description: Operation Successful
        '403':
          description: Insufficient Rights
        '404':
          description: Property not found
      security:
        - auth: []
    post: 
      description: Returns time series data for a thing property
      parameters:
      - name: thingId
        in: path
        description: ID of the thing
        required: true
        schema:
          type: string
      - name: propertyName
        in: path
        description: Name of the property
        required: true
        schema:
          type: string
      requestBody:
        description: Thing description added
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
      responses:
        '200':
          description: Operation Successful
        '403':
          description: Insufficient Rights
        '404':
          description: Property not found
      security:
        - auth: []
  /property/{thingId}/{propertyName}/count:
    get:
      description: Returns time series data for a thing property
      parameters:
      - name: thingId
        in: path
        description: ID of the thing
        required: true
        schema:
          type: string
      - name: propertyName
        in: path
        description: Name of the property
        required: true
        schema:
          type: string
      - name: start
        in: Query
        schema: 
          type: string
          format: date-time
      - name: stop
        in: Query
        schema: 
          type: string
          format: date-time
      responses:
        '200':
          description: Operation Successful
        '403':
          description: Insufficient Rights
        '404':
          description: Property not found
      security:
        - auth: []
    post: 
      description: Counts time series data for a thing property
      parameters:
      - name: thingId
        in: path
        description: ID of the thing
        required: true
        schema:
          type: string
      - name: propertyName
        in: path
        description: Name of the property
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CountQuery'
      responses:
        '200':
          description: Operation Successful
        '403':
          description: Insufficient Rights
        '404':
          description: Property not found
      security:
        - auth: []
components:
  schemas:
    Query:
      type: object
      properties: 
        start:
          type: string
          format: date-time
        stop:
          type: string
          format: date-time
    CountQuery:
      type: object
      properties: 
        start:
          type: string
          format: date-time
        stop:
          type: string
          format: date-time
        filterFuncs:
          type: array
          items:
            $ref: '#/components/schemas/FilterFunc'
        values:
          type: array
          items:
            type: string
    FilterFunc:
      type: string
      enum: [eq, ne, gt, lt, ge, le]
  securitySchemes:
    auth:
      type: oauth2
      flows: 
        authorizationCode:
          authorizationUrl: 'https://aareoniam.apps.foresight.aareon.com/auth/realms/foresight/protocol/openid-connect/auth'
          tokenUrl: 'https://aareoniam.apps.foresight.aareon.com/auth/realms/foresight/protocol/openid-connect/token'