openapi: "3.0.0"
info:
  title: History Service
  version: 0.1.0
servers:
- url: https://thing-history.apps.foresight.aareon.com/api/
  description: History Service
paths:
  /query:
    get: 
      description: Returns time series data for thing properties
      parameters:
        - name: property
          in: query
          required: true
          schema:
            type: array
            uniqueItems: true
            items:
              type: string
        - name: start
          in: query
          example: read
          required: true
          schema:
            type: string
        - name: stop
          in: query
          example: read
          schema:
            type: string
      responses:
        '200':
          description: Operation Successful
        '403':
          description: Insufficient Rights
      security:
        - auth: []
components:
  schemas:
    PropertiesQuery:
      type: object
      properties: 
        range:
          $ref: '#/components/schemas/Range'
        properties:
          type: array
          items: 
            type: string
          minItems: 1
      required: [ range, properties ]
    Range:
      type: object
      properties: 
        start: 
          type: string
          format: date-time
        stop:
          type: string
          format: date-time
      required: [ start ]
  securitySchemes:
    auth:
      type: oauth2
      flows: 
        authorizationCode:
          authorizationUrl: 'https://aareoniam.apps.foresight.aareon.com/auth/realms/foresight/protocol/openid-connect/auth'
          tokenUrl: 'https://aareoniam.apps.foresight.aareon.com/auth/realms/foresight/protocol/openid-connect/token'