version: "3.1"

services:
  history:
    build: .
    ports:
      - 9221:8080
      - 9229:9229
    environment:
      - NODE_ENV=development
      - KEYCLOAK_HOST=${KEYCLOAK_HOST}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
    volumes:
      - ./keycloak.json:/app/keycloak.json
      - ./lib:/app/lib
      - ./api-doc.yml:/app/api-doc.yml